# 11-04-2022 (DATA ANALYSTICS)


In [1]:
#DATA ANALYSTICS LIBRARY----->
#1.NUMPY------>NUMERICAL PYTHON----->1.ARRAY, 2.MATRIX, 3.TRANSPOSE, 4.
#2.PANDAS----->PANEL DATA----->
#3.MATPLOTLIB
#4.SEABORN

# 1.PANDAS--->2.MINI PROJECT

# 2.MATPLOTLIB & SEABORN------> 1. MINI PROJECT + PANDAS+MAT+SEABORN

# 3. DATA PREPROCESSING, DATA WRANGLING, OPERATION ON DATA, DESCRIBE THE DATA

# START---->DESCRIPTIVE START/ INFRENTIAL STARTS

# 1.MAJOR PROJECT

# 12-04-2022 (NUMPY)


In [2]:
#numpy----- array
import numpy as np

In [3]:
#array---->
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#type function
type(a)

numpy.ndarray

In [5]:
#ndim
a.ndim

1

In [6]:
a.shape

(9,)

In [7]:
a.size

9

In [8]:
#shape and size
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a.shape

(9,)

In [10]:
a.size

9

In [11]:
#2d data
x= np.array([[1,2,3,4,5,6,7,8,9]])

In [12]:
x

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [13]:
x.shape

(1, 9)

In [14]:
x.ndim

2

In [15]:
s = np.array([[1,2,3],[7,8,9]])
s

array([[1, 2, 3],
       [7, 8, 9]])

In [16]:
s.shape

(2, 3)

In [17]:
s = np.array([[1,2,3],[7,8]])

C:\Users\ROUSHA~1\AppData\Local\Temp/ipykernel_18480/1468163393.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  s = np.array([[1,2,3],[7,8]])


In [18]:
#check the data type of the array
type(s)

numpy.ndarray

In [19]:
s.dtype

dtype('O')

In [20]:
w = np.array([[1,2,3],[4,5,6]])

In [21]:
w.dtype

dtype('int32')

In [22]:
w.ndim

2

In [23]:
#3d data
v = np.array([[[1,2,3]]])

In [24]:
v.ndim

3

In [25]:
v.shape

(1, 1, 3)

In [26]:
v.size

3

In [27]:
v = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [28]:
v

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [29]:
v.ndim

3

In [30]:
v.shape

(1, 3, 3)

In [31]:
v.size

9

In [32]:
a=np.array([[[1,2,3],[1,2,3],[[1,2,3],[1,2,3]])

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (Temp/ipykernel_18480/2622285674.py, line 1)

In [ ]:
#wap and slice with the help of index to the data i.e 45.
a=np.array([[1,2,3],[45,78,90]])

In [ ]:
a

In [ ]:
a[1]

In [ ]:
a[1][0]

In [ ]:
#numpy----------> zeroes
np.zeros(40)

In [ ]:
#ones
np.ones(100)

In [ ]:
#arange
np.arange(10)

In [ ]:
np.arange(20,300,90)

# 13-04-2022 

In [ ]:
#ones
import numpy as np
np.ones(3)

In [ ]:
x=np.ones([5,3,8])

In [ ]:
x

In [ ]:
x.ndim

In [ ]:
s=np.ones([6,4])

In [ ]:
s

In [ ]:
s.ndim

In [ ]:
x=np.zeros([2])

In [ ]:
x

In [ ]:
#wap to add 2 list
a=[1,2,3]
b=[3,4,5]

In [ ]:
z=np.array([[1,2,3],[3,4,5]])

In [ ]:
z

In [ ]:
z.sum(axis=0)

In [ ]:
z.sum()

In [ ]:
z.sum(axis=1)

In [ ]:
x=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [ ]:
x

In [ ]:
x.sum()

In [ ]:
x.sum(axis=0)

In [ ]:
x.sum(axis=1)

In [ ]:
x.sum(axis=2)

In [ ]:
#transpose metrix
d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [ ]:
d

In [ ]:
d.T

In [ ]:
#searching / sorting
w= np.array([100,30,89,34,64,96,74])

In [ ]:
w

In [ ]:
#search
np.where(a%2==0)

In [ ]:
#sorting
w

In [ ]:
w.sort  #sort()
print(w)

In [ ]:
w.sort(-1)

In [ ]:
m= np.array([[100,30,89],[34,64,96],[74,89,78]])

In [ ]:
m

In [ ]:
#minimum
m.min()

In [ ]:
#maximum
m.max()

In [ ]:
m.mean()

In [ ]:
#argmax
#argmin
#argsort

In [ ]:
t= np.array([[1008,302,898],[347,648,964],[754,859,788]])

In [ ]:
t

In [ ]:
t.argmax()

In [ ]:
t.argmin()

In [ ]:
t.argsort()

# 14-04-2022

# PANDAS 

In [ ]:
import pandas as pd

In [ ]:
#wap to make dict!!
a={
    'Name':['Roushan', 'Rohan','Preet'],
    'age':[22,24,26],
    'marks':[200,400,600]
}

In [ ]:
a

In [ ]:
df = pd.DataFrame(a,index=[0,1,2])

In [ ]:
df

In [ ]:
df.iloc[0:1]

In [ ]:
df['Name'][2]

In [ ]:
df[['Name','marks']]

In [ ]:
df.iloc[2:3]

In [ ]:
#store the data in the form of a file
file = df.to_csv('mynewfile.csv')

In [ ]:
file

In [ ]:
#task--------> to import data to python
df1 = pd.read_csv()

In [ ]:
#task to observe data
#head #df1.head()
#tail #df1.tail()
#sample #df1.sample()

# 19-04-2022

# PANDAS PART_2

In [ ]:
#head & tail
#sample
#how to calculate null value in the data.
#isnull------------->false---------->data is present
#notnull------------>false-----------> data is not present

In [ ]:
#df.isnull().sum()
#df.notnull().sum()

In [ ]:
#graphs
import seaborn as sns

In [ ]:
#corr------->ye relateion batata hai ki kis particular column ke sath relationship kitna hai
#df.corr()


In [ ]:
#describe-----------> ye numerical data ko describe karta hai
#df.describe()

In [ ]:
#graph----->heatmap
#sns.heatmap()
#sns.heatmap(df1.corr(),annot=True)

In [ ]:
#replace
#df.replace
#df.replace--------press shift+tab to open cheat sheet
#df.replace('Gurgaon','Gurugram')

# 20-04-2022

In [ ]:
import pandas as pd
df2= pd.read_csv(r'C:\Users\ROUSHAN KUMAR\Downloads\Bengaluru_House_Data.csv')

In [ ]:
#handeling missing values
#1.delete
#2.ignore
#3.store random values


In [ ]:
#prediction with miss value < prediction with not miss value
#4.mean
#5.median
#6.mode

In [ ]:
df2

In [ ]:
#to open cheat sheet (shirt+tab)
df2.drop()

In [ ]:
# dropna--------------> drop null value
x= df2.dropna()

In [ ]:
x.isnull().sum()

In [ ]:
#srarching and sorting
#loc & iloc
#loc---------->location based searching
#iloc---------> index based location searching
df2.loc[df2['society']=='Soiewre']


In [ ]:
#use loc to search the data from df
#1. find the name and founded year of edtech companies.

In [ ]:
df3=pd.read_csv(r'C:\Users\ROUSHAN KUMAR\Downloads\Indian Startup.csv')

In [ ]:
df3

In [ ]:
df3.loc[df3['Sector']=='EdTech' or [df['Sector']=='E-commerce'[['Company/Brand','Founded']]]

# 21-04-2022
# PANDAS PART 4

In [ ]:
# find the dname and founded year of edtech + e-comm companies.
df3[df3['Sector'] == ['EdTech','E-commerce']]

In [ ]:
df3[(df3['Sector']=='Edtech') | (df['Sector']=='E-commerce')]

In [ ]:
sector=df3['Sector']=='E-commerce'

In [ ]:
sector.shape[0]

In [ ]:
#dot notation
df3.Sector

In [ ]:
df3.Founded

In [ ]:
#Data manipulation
#drop
#adding column, rows
# perform aggregation function
#iloc
df3.columns

In [ ]:
df3[df3['Founded'],2018]

In [ ]:
df3

# 25-04-2022

# PANDAS PART_5


In [ ]:
import pandas as pd

In [ ]:
df4 = pd.read_csv(r'C:\Users\ROUSHAN KUMAR\Downloads\IPL Matches 2008-2020.csv')

In [ ]:
df4

In [ ]:
df4.head()

In [ ]:
#loc----------------->location based searching!!
#iloc---------------->index based searching!!
df4.iloc[0]


In [ ]:
df4.iloc[0,3]

In [ ]:
df4.iloc [0,5]

In [ ]:
df4.columns

In [ ]:
df4.city

In [ ]:
#how many times ipl happen in banglore city
df4['city'].iloc[0]

In [ ]:
df4.iloc[df4['city']=='Bangalore']

In [ ]:
df4['city'].value_counts()

In [ ]:
df4.loc[df4['city']=='Bangalore',['city','venue']]

In [ ]:
df4.shape

In [ ]:
df4[df4['city']=='Bangalore'].value_counts

In [ ]:
#df["city"=="Bangalore"].value_counts()
df4.loc[df4['city']=='Bangalore',['player_of_match','team1']]

In [ ]:
# aggregation_function
# max,min,mean,median,avg,std_deviation,percentile
# info
df4.info()


In [ ]:
df4['result_margin'].sum()

In [ ]:
df4['result_margin'].max()

In [ ]:
df4['result_margin'].min()

In [ ]:
df4['result_margin'].mean()

# 26-04-2022

# PANDAS_PART_6

In [34]:
#GROUPBY()
#ON THE BASIS OF TOSS_DECISION WHAT WILL BE THE UPCOMING RESULT
import pandas as pd


In [35]:
df= pd.read_csv(r'C:\Users\ROUSHAN KUMAR\Downloads\IPL Matches 2008-2020.csv')

In [36]:
df

id        city        date player_of_match  \
0     335982   Bangalore  2008-04-18     BB McCullum   
1     335983  Chandigarh  2008-04-19      MEK Hussey   
2     335984       Delhi  2008-04-19     MF Maharoof   
3     335985      Mumbai  2008-04-20      MV Boucher   
4     335986     Kolkata  2008-04-20       DJ Hussey   
..       ...         ...         ...             ...   
811  1216547       Dubai  2020-09-28  AB de Villiers   
812  1237177       Dubai  2020-11-05       JJ Bumrah   
813  1237178   Abu Dhabi  2020-11-06   KS Williamson   
814  1237180   Abu Dhabi  2020-11-08      MP Stoinis   
815  1237181       Dubai  2020-11-10        TA Boult   

                                          venue  neutral_venue  \
0                         M Chinnaswamy Stadium              0   
1    Punjab Cricket Association Stadium, Mohali              0   
2                              Feroz Shah Kotla              0   
3                              Wankhede Stadium              0   
4                                  Eden Gardens              0   
..                                          ...            ...   
811         Dubai International Cricket Stadium              0   
812         Dubai International Cricket Stadium              0   
813                        Sheikh Zayed Stadium              0   
814                        Sheikh Zayed Stadium              0   
815         Dubai International Cricket Stadium              0   

                           team1                        team2  \
0    Royal Challengers Bangalore        Kolkata Knight Riders   
1                Kings XI Punjab          Chennai Super Kings   
2               Delhi Daredevils             Rajasthan Royals   
3                 Mumbai Indians  Royal Challengers Bangalore   
4          Kolkata Knight Riders              Deccan Chargers   
..                           ...                          ...   
811  Royal Challengers Bangalore               Mumbai Indians   
812               Mumbai Indians               Delhi Capitals   
813  Royal Challengers Bangalore          Sunrisers Hyderabad   
814               Delhi Capitals          Sunrisers Hyderabad   
815               Delhi Capitals               Mumbai Indians   

                     toss_winner toss_decision                       winner  \
0    Royal Challengers Bangalore         field        Kolkata Knight Riders   
1            Chennai Super Kings           bat          Chennai Super Kings   
2               Rajasthan Royals           bat             Delhi Daredevils   
3                 Mumbai Indians           bat  Royal Challengers Bangalore   
4                Deccan Chargers           bat        Kolkata Knight Riders   
..                           ...           ...                          ...   
811               Mumbai Indians         field  Royal Challengers Bangalore   
812               Delhi Capitals         field               Mumbai Indians   
813          Sunrisers Hyderabad         field          Sunrisers Hyderabad   
814               Delhi Capitals           bat               Delhi Capitals   
815               Delhi Capitals           bat               Mumbai Indians   

      result  result_margin eliminator method      umpire1         umpire2  
0       runs          140.0          N    NaN    Asad Rauf     RE Koertzen  
1       runs           33.0          N    NaN    MR Benson      SL Shastri  
2    wickets            9.0          N    NaN    Aleem Dar  GA Pratapkumar  
3    wickets            5.0          N    NaN     SJ Davis       DJ Harper  
4    wickets            5.0          N    NaN    BF Bowden     K Hariharan  
..       ...            ...        ...    ...          ...             ...  
811      tie            NaN          Y    NaN  Nitin Menon      PR Reiffel  
812     runs           57.0          N    NaN  CB Gaffaney     Nitin Menon  
813  wickets            6.0          N    NaN   PR Reiffel          S Ravi  
814     runs           17.0          N    Na

In [37]:
df.result

0         runs
1         runs
2      wickets
3      wickets
4      wickets
        ...   
811        tie
812       runs
813    wickets
814       runs
815    wickets
Name: result, Length: 816, dtype: object

In [45]:
df.groupby(['toss_decision'])[['winner']].max()

C:\Users\ROUSHA~1\AppData\Local\Temp/ipykernel_18480/4068954086.py:1: FutureWarning: Dropping invalid columns in DataFrameGroupBy.max is deprecated. In a future version, a TypeError will be raised. Before calling .max, select only columns which should be valid for the function.
  df.groupby(['toss_decision'])[['winner']].max()


Empty DataFrame
Columns: []
Index: [bat, field]

In [53]:
df.groupby(["toss_decision","result"]).mean()

id  neutral_venue  result_margin
toss_decision result                                              
bat           runs     645765.198630       0.150685      28.013699
              tie      960977.400000       0.200000            NaN
              wickets  668684.184524       0.125000       6.422619
field         runs     810572.522936       0.059633      32.178899
              tie      882998.250000       0.125000            NaN
              wickets  818904.966292       0.071161       6.202247

In [70]:
#wap on the basis of city arrange the data into assending order and decending order
df.groupby(by='city').sort


True

In [72]:
df.sort_values('city',ascending=True).groupby('team1').head()

id           city        date player_of_match  \
405   729293      Abu Dhabi  2014-04-21        SK Raina   
416   729315      Abu Dhabi  2014-04-29     JP Faulkner   
412   729307      Abu Dhabi  2014-04-26  Sandeep Sharma   
411   729305      Abu Dhabi  2014-04-26        PV Tambe   
814  1237180      Abu Dhabi  2020-11-08      MP Stoinis   
..       ...            ...         ...             ...   
536   980939           Pune  2016-04-24        SA Yadav   
605  1082620           Pune  2017-04-26      RV Uthappa   
532   980931           Pune  2016-04-22  AB de Villiers   
614  1082629           Pune  2017-05-01       BA Stokes   
556   980979  Visakhapatnam  2016-05-10         A Zampa   

                                                 venue  neutral_venue  \
405                               Sheikh Zayed Stadium              1   
416                               Sheikh Zayed Stadium              1   
412                               Sheikh Zayed Stadium              1   
411                               Sheikh Zayed Stadium              1   
814                               Sheikh Zayed Stadium              0   
..                                                 ...            ...   
536            Maharashtra Cricket Association Stadium              0   
605            Maharashtra Cricket Association Stadium              0   
532            Maharashtra Cricket Association Stadium              0   
614            Maharashtra Cricket Association Stadium              0   
556  Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...              0   

                       team1                        team2  \
405      Chennai Super Kings             Delhi Daredevils   
416    Kolkata Knight Riders             Rajasthan Royals   
412    Kolkata Knight Riders              Kings XI Punjab   
411         Rajasthan Royals  Royal Challengers Bangalore   
814           Delhi Capitals          Sunrisers Hyderabad   
..                       ...                          ...   
536  Rising Pune Supergiants        Kolkata Knight Riders   
605   Rising Pune Supergiant        Kolkata Knight Riders   
532  Rising Pune Supergiants  Royal Challengers Bangalore   
614   Rising Pune Supergiant                Gujarat Lions   
556  Rising Pune Supergiants          Sunrisers Hyderabad   

                 toss_winner toss_decision                       winner  \
405      Chennai Super Kings           bat          Chennai Super Kings   
416         Rajasthan Royals           bat             Rajasthan Royals   
412    Kolkata Knight Riders         field              Kings XI Punjab   
411         Rajasthan Royals         field             Rajasthan Royals   
814           Delhi Capitals           bat               Delhi Capitals   
..                       ...           ...                          ...   
536    Kolkata Knight Riders         field        Kolkata Knight Riders   
605    Kolkata Knight Riders         field        Kolkata Knight Riders   
532  Rising Pune Supergiants         field  Royal Challengers Bangalore   
614   Rising Pune Supergiant         field       Rising Pune Supergiant   
556      Sunrisers Hyderabad           bat          Sunrisers Hyderabad   

      result  result_margin eliminator method          umpire1         umpire2  
405     runs           93.0          N    NaN   RK Illingworth   C Shamshuddin  
416      tie            NaN          Y    NaN        Aleem Dar    AK Chaudhary  
412     runs           23.0          N    NaN  HDPK Dharmasena  RK Illingworth  
411  wickets            6.0          N    NaN  HDPK Dharmasena   C Shamshuddin  
814     runs           17.0          N    NaN       PR Reiffel          S Ravi  
..       ...            ...        ...    ...              ...             ...  
536  wickets            2.0          N    NaN      CB Gaffaney  A Nand Kishore  
605  wickets            7.0          N    NaN      AY Dandekar        NJ Llong  
532     runs           13.0          N    NaN      CB Gaffane

In [78]:
df.groupby(by = 'city',sort=False).head()

id        city        date player_of_match  \
0     335982   Bangalore  2008-04-18     BB McCullum   
1     335983  Chandigarh  2008-04-19      MEK Hussey   
2     335984       Delhi  2008-04-19     MF Maharoof   
3     335985      Mumbai  2008-04-20      MV Boucher   
4     335986     Kolkata  2008-04-20       DJ Hussey   
..       ...         ...         ...             ...   
766  1216502     Sharjah  2020-10-31  Sandeep Sharma   
768  1216504       Dubai  2020-09-30     Shivam Mavi   
771  1216507       Dubai  2020-10-11       R Tewatia   
773  1216509     Sharjah  2020-10-17        S Dhawan   
774  1216510       Dubai  2020-09-24        KL Rahul   

                                          venue  neutral_venue  \
0                         M Chinnaswamy Stadium              0   
1    Punjab Cricket Association Stadium, Mohali              0   
2                              Feroz Shah Kotla              0   
3                              Wankhede Stadium              0   
4                                  Eden Gardens              0   
..                                          ...            ...   
766                     Sharjah Cricket Stadium              0   
768         Dubai International Cricket Stadium              0   
771         Dubai International Cricket Stadium              0   
773                     Sharjah Cricket Stadium              0   
774         Dubai International Cricket Stadium              0   

                           team1                        team2  \
0    Royal Challengers Bangalore        Kolkata Knight Riders   
1                Kings XI Punjab          Chennai Super Kings   
2               Delhi Daredevils             Rajasthan Royals   
3                 Mumbai Indians  Royal Challengers Bangalore   
4          Kolkata Knight Riders              Deccan Chargers   
..                           ...                          ...   
766  Royal Challengers Bangalore          Sunrisers Hyderabad   
768        Kolkata Knight Riders             Rajasthan Royals   
771          Sunrisers Hyderabad             Rajasthan Royals   
773          Chennai Super Kings               Delhi Capitals   
774              Kings XI Punjab  Royal Challengers Bangalore   

                     toss_winner toss_decision                       winner  \
0    Royal Challengers Bangalore         field        Kolkata Knight Riders   
1            Chennai Super Kings           bat          Chennai Super Kings   
2               Rajasthan Royals           bat             Delhi Daredevils   
3                 Mumbai Indians           bat  Royal Challengers Bangalore   
4                Deccan Chargers           bat        Kolkata Knight Riders   
..                           ...           ...                          ...   
766          Sunrisers Hyderabad         field          Sunrisers Hyderabad   
768             Rajasthan Royals         field        Kolkata Knight Riders   
771          Sunrisers Hyderabad           bat             Rajasthan Royals   
773          Chennai Super Kings           bat               Delhi Capitals   
774  Royal Challengers Bangalore         field              Kings XI Punjab   

      result  result_margin eliminator method                umpire1  \
0       runs          140.0          N    NaN              Asad Rauf   
1       runs           33.0          N    NaN              MR Benson   
2    wickets            9.0          N    NaN              Aleem Dar   
3    wickets            5.0          N    NaN               SJ Davis   
4    wickets            5.0          N    NaN              BF Bowden   
..       ...            ...        ...    ...                    ...   
766  wickets            5.0          N    NaN  KN Ananthapadmanabhan   
768     runs           37.0          N    NaN  KN Ananthapadmanabhan   
771  wickets            5.0          N    NaN               YC Barde   
773  wickets            5.0          N    NaN  KN Ananthapadmanabhan   
774     runs          

In [100]:
#merge()
df1 = pd.DataFrame({'A': ['a', 'b', 'c', 'd'],'value': [1, 2, 3, 5]})
df1

#concate()
#append()

A  value
0  a      1
1  b      2
2  c      3
3  d      5

In [103]:
df2 = pd.DataFrame({'B': ['a', 'b', 'c', 'd'],'value': [6, 7, 8, 9]})
df2

B  value
0  a      6
1  b      7
2  c      8
3  d      9

In [107]:
pd.merge(df1, df2,how='left')

A  value    B
0  a      1  NaN
1  b      2  NaN
2  c      3  NaN
3  d      5  NaN